# Numerical Linear Algebra (FMNN01)
__LTH Fall 2019__
## Assignment 4
__Jonas Lundgren__

In [1]:
from scipy.linalg import qr, lu, svd, inv, hilbert, invhilbert
import numpy as np
import matplotlib.pyplot as plt

We start by constructing a matirx __X__ of size $4\times5$ of with rank 3.

In [2]:
U = np.random.random((4,4))
V = np.random.random((5,5))
P = np.array([[1,0,0,0,0],
              [0,1,0,0,0],
              [0,0,1,0,0],
              [0,0,0,0,0]])
X = U@P@V
print("Matrix X :\n", X)
print("Rank of X :", np.linalg.matrix_rank(X))

Matrix X :
 [[0.47288936 0.33811059 1.39338585 0.95816062 1.25760437]
 [0.1951277  0.13642007 0.46762341 0.61364138 0.52429056]
 [0.94129903 0.53286083 1.74989052 1.27717103 1.6322059 ]
 [0.93705805 0.52402269 1.68578736 1.26769428 1.58751471]]
Rank of X : 3


In [3]:
def rank_by_qr(X):
    Q,R = qr(X)
    
    m, n = np.shape(R)
    zero_rows = np.array([np.allclose(R[i, :], np.zeros(n)) for i in range(m)])
    
    return sum(~zero_rows)

print("Rank of X from QR:", rank_by_qr(X))

Rank of X from QR: 3


In [4]:
def rank_by_lu(X):
    P, L, U = lu(X)
    
    m, n = np.shape(U)
    zero_rows = np.array([np.allclose(U[i, :], np.zeros(n)) for i in range(m)])
    
    return sum(~zero_rows)

print("Rank of X from LU:", rank_by_lu(X))

Rank of X from LU: 3


In [5]:
def rank_by_svd(X):
    U, S, Vt = svd(X)
    
    return sum(~np.isclose(S, 0))

print("Rank of X from SVD:", rank_by_svd(X))

Rank of X from SVD: 3


In [6]:
def kahan_matrix(theta = 1.2, n = 90):
    s = np.sin(theta)
    c = np.cos(theta)
    
    S = np.diag([s**i for i in range(n)])
    R = np.triu(-c * np.ones([n,n]))
    np.fill_diagonal(R, 1)
    
    return (S @ R).T @ (S @ R)

In [11]:
K = kahan_matrix(theta = 1.2, n = 90)

print("Rank from QR :", rank_by_qr(K))
print("Rank from LU :", rank_by_lu(K))
print("Rank from SVD :", rank_by_svd(K))

Rank from QR : 90
Rank from LU : 90
Rank from SVD : 89


In [12]:
np.linalg.matrix_rank(K)

89

We can see that the different methods gives different results in terms of the rank of the matrix. Ultimately it comes down to what we consider to be a zero in the matrix. I've used the functions `numpy.isclose` and `numpy.allclose` to determine the rank both of which have a pre set tolorance of $10^{-8}$. If we were to increse the tolorance we would be less strict in what we would consider to be equal to 0 and therefore give a lower rank of the matrix. We see that in this case the function `np.linalg.matrix_rank` generated the same rank i.e. 89 as my implementation of calculating the rank using SVD while using LU and QR to determine the rank resulted in rank 90 of the Kahan matrix.

## Task 2