## Task 7

In [1]:
import numpy as np
from scipy.linalg import *

In [2]:
u = np.array([1,2,3,4,5])
v = np.array([6,5,4,3,2])

In [3]:
A = np.outer(u,v)
A

array([[ 6,  5,  4,  3,  2],
       [12, 10,  8,  6,  4],
       [18, 15, 12,  9,  6],
       [24, 20, 16, 12,  8],
       [30, 25, 20, 15, 10]])

In [4]:
U,S,Vt = svd(A)

In [5]:
np.round(S)

array([70.,  0.,  0.,  0.,  0.])

In [6]:
print("sigma 1 : ", S[0])
print("2norm(A): ", norm(A))

sigma 1 :  70.35623639735145
2norm(A):  70.35623639735144


In [7]:
(U*norm(u))[:,0]

array([-1., -2., -3., -4., -5.])

In [8]:
(Vt*norm(v))[0,:]

array([-6., -5., -4., -3., -2.])